VAR: sitat.lastå – skjerming av sitat i pipelinen
$ unset AP_SETVAR
$ echo Han omtaler antallet søknader som «et meget stort antall» i konsesjonsrunden|apertium -d . nob-nno_e
Han omtaler talet på søknader som «eit svært stort tal» i konsesjonsrunden

$ export AP_SETVAR=sitat.lastå
$ echo Han omtaler antallet søknader som «et meget stort antall» i konsesjonsrunden|apertium -d . nob-nno_e
Han omtaler talet på søknader som «et meget stort antall» i konsesjonsrunden

For no berre «.*», men det kan utvidast til fleire variantar, og det
er mogleg å laga unntak og meir nyanserte system vha. CG-reglar.

diff --git a/t/motvariant b/t/motvariant
--- a/t/motvariant
+++ b/t/motvariant
@@ -38,8 +38,9 @@ selftest () {
                 continue
             fi
             grep -q -w -F "VAR:$x" apertium-nno-nob.nob-nno.biprefs.rlx          \
+            || grep -q -w -F "VAR:$x" merge-quotes.rlx                           \
             || grep -q -F "sdef n=\"v:$x\"" ../apertium-nno/apertium-nno.nno.dix \
-            || echo "WARNING: v:$x not found in nno.dix nor biprefs.rlx" >&2
+            || echo "WARNING: v:$x not found in nno.dix / merge-quotes.rlx / biprefs.rlx" >&2
         done
     )
 }
