t/progression expect cappelen

diff --git a/t/progression b/t/progression
--- a/t/progression
+++ b/t/progression
@@ -70,6 +70,23 @@ $0 expect         # add sentence from stdin as new test with current as expected
     exit 1
 }
 
+get-mode () {
+    # TODO: Get mode from file name (but need an unambiguous file name scheme then)
+    if [[ $1 = *cappelen* ]]; then
+        echo nob-nno
+    else
+        echo nob-nno_e
+    fi
+}
+
+setvars () {
+    if [[ $1 = *cappelen* ]]; then
+        # shellcheck source=./cappelen
+        source t/cappelen
+    else
+        export AP_SETVAR=''
+    fi
+}
 
 [[ $# -lt 1 || $# -gt 2 ]] && assert-usage
 
@@ -81,15 +98,8 @@ case $1 in
         for f in tests/*.input.txt; do
             name="$(basename "${f%.input.txt}")"
             [[ ${name} = *${namefilter}* ]] || continue
-            # TODO: Get mode from file name (but need an unambiguous file name scheme then)
-            if [[ ${name} = *nob-nno_cappelen ]]; then
-                mode=nob-nno
-                # shellcheck source=./cappelen
-                source t/cappelen
-            else
-                mode=nob-nno_e
-                export AP_SETVAR=''
-            fi
+            mode=$(get-mode "${name}")
+            setvars "${name}"
             apertium -d . "${mode}" < tests/"${name}".input.txt >tests/out/"${name}.${step}".current.txt
         done
         ;;
@@ -108,15 +118,21 @@ case $1 in
         difs gold "${namefilter}"
         ;;
     expect)
-        mode=nob-nno_e
         if [[ -z "${namefilter}" ]]; then echo "Needs a test set, e.g. 'ymse'"; exit 1; fi
-        inputf=tests/"${namefilter}"-${mode}.input.txt
-        expf=tests/out/"${namefilter}"-${mode}.all.expected.txt
-        goldf=tests/"${namefilter}"-${mode}.all.gold.txt
-        if [[ ! -e "${inputf}" ]]; then echo "Unknown test set '${namefilter}'"; echo "(couldn't find file ${inputf} – try 'ymse' if unsure)"; exit 1; fi
-        input=$(cat)
-        [[ "${input}" = *[.?\!] ]] || input="${input}." # ensure final punctuation
-        echo "${input}" | tee -a "${inputf}" | apertium -d . "${mode}" | tee -a "${expf}" "${goldf}"
+        seen=false
+        for f in tests/*.input.txt; do
+            name="$(basename "${f%.input.txt}")"
+            [[ ${name} = *${namefilter}* ]] || continue
+            mode=$(get-mode "${name}")
+            setvars "${name}"
+            expf=tests/out/"${name}".all.expected.txt
+            goldf=tests/"${name}".all.gold.txt
+            seen=true
+            input=$(cat)
+            [[ "${input}" = *[.?\!] ]] || input="${input}." # ensure final punctuation
+            echo "${input}" | tee -a "${f}" | apertium -d . "${mode}" | tee -a "${expf}" "${goldf}"
+        done
+        if ! ${seen}; then echo "Unknown test set '${namefilter}'"; echo "(couldn't find file matching tests/*${namefilter}*.input.txt – try 'ymse' if unsure)"; exit 1; fi
         ;;
     *)
         assert-usage
