update tests scripts

diff --git a/t/wiki-tests b/t/wiki-tests
--- a/t/wiki-tests
+++ b/t/wiki-tests
@@ -2,37 +2,11 @@
 
 set -e -u
 
+######## Globals:
+
+# You shouldn't have to change this unless the wiki gets a new host:
 declare -r PACKAGE=$(grep ^PACKAGE= "$(dirname $0)/../config.log" |grep -o "apertium-[^']*") # e.g. apertium-sme-nob
 declare -r BASEURL="http://wiki.apertium.org/wiki/${PACKAGE}"
-
-UPDATE=false
-ONLYPASS=false
-ONLYFAIL=false
-while getopts "upf" opt; do
-     case "$opt" in
-         u) UPDATE=true;;
-         f) ONLYFAIL=true;;
-         p) ONLYPASS=true;;
-	 \?) echo "Invalid option" >&2; exit 2;;
-	 :) echo "Option requires an argument." >&2; exit 2;;
-     esac
-done
-shift "$((OPTIND-1))"
-if [[ $# -ne 3 ]] || ( $ONLYPASS && $ONLYFAIL ); then
-    echo "Usage: $0 [-u] [-p|-f] {Regression,Pending} srclang trglang"
-    echo "-u       Use updated tests"
-    echo "-p       Show only passing tests"
-    echo "-f       Show only failing tests"
-    exit 2
-fi
-declare -r TESTTYPE="$1_tests"
-declare -r SRCLANG="$2"
-declare -r TRGLANG="$3"
-
-# Derived options:
-declare -r MODE="$SRCLANG-$TRGLANG"
-declare -r HTML="$(dirname $0)/${TESTTYPE}.html"
-
 
 # Workarounds for Mac's:
 SED=sed
@@ -42,20 +16,25 @@ fi
 declare -r SED
 
 
+######## Functions:
 
 fetchtests () {
-    if ${UPDATE}; then
+    local -r update=$1
+    local -r testtype=$2
+    local -r html=$3
+
+    if ${update}; then
 	tmp=$(mktemp -t wiki-tests.html.XXXXXXXXXX)
-	if wget -O "${tmp}" -q "${BASEURL}/${TESTTYPE}" && [[ -s "${tmp}" ]]; then
-	    mv "${tmp}" "${HTML}"
+	if wget -O "${tmp}" -q "${BASEURL}/${testtype}" && [[ -s "${tmp}" ]]; then
+	    mv "${tmp}" "${html}"
 	else
 	    rm "${tmp}"
-	    echo "Couldn't fetch ${BASEURL}/${TESTTYPE}" >&2
+	    echo "Couldn't fetch ${BASEURL}/${testtype}" >&2
 	fi
     fi
 
-    if [[ ! -s "${HTML}" ]]; then
-	echo "${HTML} does not exist or is empty (use '-u' option)" >&2
+    if [[ ! -s "${html}" ]]; then
+	echo "${html} does not exist or is empty (use '-u' option)" >&2
 	exit 1
     fi
 }
@@ -64,24 +43,27 @@ cleantst () {
     $SED 's/^ *//; s/ *$//; s/\([^,.?!:;]\)$/\1./g; s/   */ /g'
 }
 cleansrc () {
-    grep -o "<li> (${SRCLANG})[^→]*" |$SED "s%</*[^>]*>%%g; s% *(${SRCLANG}) *%%" | cleantst
+    local -r srclang=$1
+    grep -o "<li> (${srclang})[^→]*" |$SED "s%</*[^>]*>%%g; s% *(${srclang}) *%%" | cleantst
 }
 cleantrg () {
-    grep -o "<li> (${SRCLANG}).*" | $SED 's%[^→]*→ *%%; s%::.*%%'  | cleantst
+    local -r srclang=$1
+    grep -o "<li> (${srclang}).*" | $SED 's%[^→]*→ *%%; s%::.*%%'  | cleantst
 }
 
 summary () {
+    local -r mode=$1 srclist=$2 trglist=$3 tstlist=$4 onlyfail=$5 onlypass=$6
     # Output the MT vs ref translations:
-    declare -i total=0
-    declare -i correct=0
-    declare -r sep=''
+    local -i total=0
+    local -i correct=0
+    local -r sep=''
     while IFS="${sep}" read -r src trg tst; do
 	if [[ "${trg}" = "${tst}" ]]; then
 	    (( ++correct ))
-	    $ONLYFAIL || printf "%s\t  %s\nWORKS\t  %s\n\n\n" "${MODE}" "${src}" "${tst}"
+	    $onlyfail || printf "%s\t  %s\nWORKS\t  %s\n\n\n" "${mode}" "${src}" "${tst}"
 	else
 	    (( 1 ))
-	    $ONLYPASS || printf "%s\t  %s\n\t- %s\n\t+ %s\n\n\n" "${MODE}" "${src}" "${trg}" "${tst}"
+	    $onlypass || printf "%s\t  %s\n\t- %s\n\t+ %s\n\n\n" "${mode}" "${src}" "${trg}" "${tst}"
 	fi
 	(( ++total ))
     done < <(paste -d "${sep}" "${srclist}" "${trglist}" "${tstlist}")
@@ -112,22 +94,52 @@ showrevisions () {
     done
 }
 
-cleanup () {
-    rm -f "${srclist}" "${trglist}" "${tstlist}"
-}
-trap 'cleanup' EXIT
-srclist=$(mktemp -t "tmp.${SRCLANG}-src.XXXXXXXXXX")
-trglist=$(mktemp -t "tmp.${SRCLANG}-trg.XXXXXXXXXX")
-tstlist=$(mktemp -t "tmp.${SRCLANG}-tst.XXXXXXXXXX")
+main () {
+    # Parse options:
+    update=false
+    onlypass=false
+    onlyfail=false
+    while getopts "upf" opt; do
+        case "$opt" in
+            u) update=true;;
+            f) onlyfail=true;;
+            p) onlypass=true;;
+	    \?) echo "Invalid option" >&2; exit 2;;
+	    :) echo "Option requires an argument." >&2; exit 2;;
+        esac
+    done
+    shift "$((OPTIND-1))"
+    if [[ $# -ne 2 ]] || ( ${onlypass} && ${onlyfail} ); then
+        echo "Usage: $0 [-u] [-p|-f] {Regression,Pending} srclang-trglang"
+        echo "-u       Use updated tests"
+        echo "-p       Show only passing tests"
+        echo "-f       Show only failing tests"
+        exit 2
+    fi
+    declare -r testtype="$1_tests"
+    declare -r srclang="${2%%-*}"
+    declare -r trglang="${2##*-}"
 
-showrevisions
-printf "Running $1-tests with mode \"${MODE}\" "; ${UPDATE} && printf "with updated tests "; echo "..."
-echo
-fetchtests
-cleansrc < "${HTML}" > "${srclist}"
-cleantrg < "${HTML}" > "${trglist}"
-(
-    set -o pipefail
-    apertium -d . "${MODE}" < "${srclist}" | cleantst > "${tstlist}"
-)
-summary
+    # Derived options:
+    declare -r mode="${srclang}-${trglang}"
+    declare -r html="$(dirname $0)/${testtype}.html"
+
+    srclist=$(mktemp -t "${mode}-src.XXXXXXXXXX")
+    trglist=$(mktemp -t "${mode}-trg.XXXXXXXXXX")
+    tstlist=$(mktemp -t "${mode}-tst.XXXXXXXXXX")
+    trap "rm -f \"${srclist}\" \"${trglist}\" \"${tstlist}\"" EXIT
+
+    showrevisions
+    printf "Running $1-tests with mode \"${mode}\" "; ${update} && printf "with updated tests "; echo "..."
+    echo
+    fetchtests "${update}" "${testtype}" "${html}"
+    cleansrc "${srclang}" < "${html}" > "${srclist}"
+    cleantrg "${srclang}" < "${html}" > "${trglist}"
+    (
+        set -o pipefail
+        apertium -d . "${mode}" < "${srclist}" | cleantst > "${tstlist}"
+    )
+    summary "${mode}" "${srclist}" "${trglist}" "${tstlist}" "${onlyfail}" "${onlypass}"
+}
+
+main "$@"
